CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS ${MYSQL_USER}@'%' IDENTIFIED BY ${MYSQL_PASSWORD};
GRANT ALL PRIVILEGES ON wordpress.* TO ${MYSQL_USER}@'%';
FLUSH PRIVILEGES;
ALTER USER ${MYSQL_ROOT_USER}@'localhost' IDENTIFIED BY ${MYSQL_ROOT_PASSWORD};
